CREATE DATABASE PIZZA;
USE PIZZA;
CREATE TABLE ORDERS(
ORDER_ID INT NOT NULL ,
ORDER_DATE DATE NOT NULL,
ORDER_TIME TIME NOT NULL,
PRIMARY KEY (ORDER_ID)
);

CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID INT NOT NULL AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    PIZZA_ID VARCHAR(50) NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (ORDER_DETAIL_ID)
);
use pizza;